#!/usr/bin/env bash
echo "must be in dir with the manage.py in a Django project"
read -p "Are you sure? " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # clear db
    find . -path "*/migrations/*.pyc"  -delete
    find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
    
    rm "db.sqlite3"
    echo "Django db and migrations cleared"
fi

