#!/usr/bin/env bash
echo "must be in dir with the manage.py in a Django project"
read -p "Are you sure? " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # clear db
    find . -path "cfc_report/migrations/*.pyc"  -delete
    find . -path "cfc_report/migrations/*.py" -not -name "__init__.py" -delete
    
    rm "db.sqlite3"
    echo "Django db and migrations cleared"
fi

# make the tables
python manage.py migrate
# run python to populate test data
echo "from cfc_report.services import database as db; db.populate_database();" | python manage.py shell 



