# Generated by Django 5.1.1 on 2024-10-06 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("cfc_id", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("cfc_id", models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name="report",
            name="tournament_director",
        ),
        migrations.RemoveField(
            model_name="report",
            name="tournament_organizer",
        ),
        migrations.AddField(
            model_name="report",
            name="TD_cfc",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 10, 6, 0, 3, 7, 7574, tzinfo=datetime.timezone.utc
                ),
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="TO_cfc",
            field=models.CharField(default=999999, max_length=6),
            preserve_default=False,
        ),
    ]
