# Generated by Django 5.1.1 on 2024-10-09 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_tournament_tournamentorganizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="cfc_id",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="TD_cfc",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="TO_cfc",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tournamentdirector",
            name="cfc_id",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ]
            ),
        ),
    ]
